### ISSUE TITLE
why V3.5.1 Script Validation Error？

### ISSUE THREAD

**Issue by huangchuanyu** [naver/ngrinder#657] opened 2020-09-23 11:07 UTC
script/api/validate 500
error message："Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.ngrinder.common.util.SystemInfoUtils"

**Comment by donggyu04** [comment] 2020-09-23 11:36
@huangchuanyu 

Could you describe your situation in more detail?

1.  OS
2. JDK version
3. How to run ngrinder
4. Your test script (if possible)
5. Steps to reproduce the bug

**Comment by huangchuanyu** [comment] 2020-09-24 07:07
windows10  
jdk 1.8.0_717
run through java -jar
Just a normal post request，and performance testing is available

**Comment by 18516329677** [comment] 2020-10-20 10:11
this issue still exist in version 3.5.2, i run ngrinder with idea or java commandline, and when i try to validate script in script detail, the validate api will show 500: java.lang.NoSuchMethodError: com.sun.jna.platform.win32.Kernel32.VerSetConditionMask(JIB)J. but when i run ngrinder with tomcat, validate is ok

**Comment by kdw9502** [comment] 2020-12-22 05:23
this issue still exist in 3.5.3 for all scripts

/script/api/validate 

return this message

{
  "message" : "Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.ngrinder.common.util.SystemInfoUtils",
  "success" : false,
  "stackTrace" : "org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.ngrinder.common.util.SystemInfoUtils\r\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\r\n\tat org.ngrinder.security.PluggablePreAuthFilter.doFilter(PluggablePreAuthFilter.java:52)\r\n\tat org.ngrinder.infra.servlet.PluggableServletFilter.doFilter(PluggableServletFilter.java:61)\r\n\tat org.ngrinder.security.PluggablePreAuthFilter.doFilter(PluggablePreAuthFilter.java:52)\r\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)\r\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\r\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\nCaused by: java.lang.NoClassDefFoundError: Could not initialize class org.ngrinder.common.util.SystemInfoUtils\r\n\tat net.grinder.engine.agent.PropertyBuilder.buildJVMArgumentWithoutMemory(PropertyBuilder.java:203)\r\n\tat net.grinder.engine.agent.LocalScriptTestDriveService.doValidate(LocalScriptTestDriveService.java:131)\r\n\tat org.ngrinder.script.service.ScriptValidationService.validate(ScriptValidationService.java:117)\r\n\tat org.ngrinder.script.controller.FileEntryApiController.validate(FileEntryApiController.java:392)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\t... 7 more\r\n"
}

**Comment by junoyoon** [comment] 2020-12-22 05:28
@donggyu04 check it in windows..

**Comment by donggyu04** [comment] 2020-12-22 06:58
@kdw9502 

Hi, It seems `jna-platform` library version issue.
In windows, `oshi` linked with a lower version `jna-platform` that transitive from another libs.

I will fix it
Thanks

**Comment by donggyu04** [comment] 2021-04-16 02:53
Fixed by #716

**Closed by donggyu04** 2021-04-16 02:53 UTC

**Comment by colin-lee** [comment] 2022-10-14 13:56
same problem on 3.5.6, docker

**Comment by matieqiang** [comment] 2023-05-06 06:01
3.5.8

**Comment by junoyoon** [comment] 2023-05-06 14:47
@donggyu04 do we check oshi again?

**Comment by ffflight** [comment] 2023-09-08 11:46
Tested with tomcat 9, so I switched to a different image.
